name: astro
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: 
  sdk: '>=2.16.1 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  widgetbook: 2.0.5-beta
  auto_size_text: 3.0.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^1.0.0
flutter: 
  uses-material-design: true
  assets: 
    - packages/astro/assets/images/7_195.png
    - packages/astro/assets/images/7_206.png
    - packages/astro/assets/images/7_211.png
    - packages/astro/assets/images/7_212.png
    - packages/astro/assets/images/7_214.png
    - packages/astro/assets/images/7_216.png
    - packages/astro/assets/images/7_220.png
    - packages/astro/assets/images/7_225.png
    - packages/astro/assets/images/7_226.png
    - packages/astro/assets/images/7_228.png
    - packages/astro/assets/images/7_230.png
    - packages/astro/assets/images/9_304.png
    - packages/astro/assets/images/7_278.png
    - packages/astro/assets/images/7_303.png
    - packages/astro/assets/images/7_195.png
    - packages/astro/assets/images/7_206.png
    - packages/astro/assets/images/7_211.png
    - packages/astro/assets/images/7_212.png
    - packages/astro/assets/images/7_214.png
    - packages/astro/assets/images/7_216.png
    - packages/astro/assets/images/7_220.png
    - packages/astro/assets/images/7_225.png
    - packages/astro/assets/images/7_226.png
    - packages/astro/assets/images/7_228.png
    - packages/astro/assets/images/7_230.png
    - packages/astro/assets/images/9_304.png
    - packages/astro/assets/images/7_278.png
    - packages/astro/assets/images/7_303.png
    - packages/astro/assets/images/7_195.png
    - packages/astro/assets/images/7_206.png
    - packages/astro/assets/images/7_211.png
    - packages/astro/assets/images/7_212.png
    - packages/astro/assets/images/7_214.png
    - packages/astro/assets/images/7_216.png
    - packages/astro/assets/images/7_220.png
    - packages/astro/assets/images/7_225.png
    - packages/astro/assets/images/7_226.png
    - packages/astro/assets/images/7_228.png
    - packages/astro/assets/images/7_230.png
    - packages/astro/assets/images/9_304.png
    - packages/astro/assets/images/7_278.png
    - packages/astro/assets/images/7_303.png
    - packages/astro/assets/images/7_195.png
    - packages/astro/assets/images/7_206.png
    - packages/astro/assets/images/7_211.png
    - packages/astro/assets/images/7_212.png
    - packages/astro/assets/images/7_214.png
    - packages/astro/assets/images/7_216.png
    - packages/astro/assets/images/7_220.png
    - packages/astro/assets/images/7_225.png
    - packages/astro/assets/images/7_226.png
    - packages/astro/assets/images/7_228.png
    - packages/astro/assets/images/7_230.png
    - packages/astro/assets/images/9_304.png
    - packages/astro/assets/images/7_278.png
    - packages/astro/assets/images/7_303.png
